"""PDF specialist coordinator runtime."""

from .contracts import (
    ConflictRecord,
    CoordinatorResult,
    MergeResult,
    ProposalClaim,
    RepairAction,
    RepairContext,
    RepairProposal,
    ViolationRef,
)
from .coordinator import (
    PDFRepairCoordinator,
    classify_violation_domain,
    merge_specialist_proposals,
    normalize_acceptance_violations,
    run_specialist_pdf_repair,
    summarize_coordinator_trace,
)
from .export import (
    append_export_record,
    build_benchmark_record,
    build_coordinator_export_record,
    count_acceptance_warnings,
)
from .benchmark import (
    BenchmarkManifest,
    BenchmarkManifestEntry,
    aggregate_benchmark_rows,
    build_residual_benchmark_manifest,
    compute_document_hash,
    dominant_domain_from_counts,
    load_benchmark_manifest,
    ResidualCandidateResult,
    run_benchmark_entry,
    run_discovery_seed,
    run_manifest_benchmark,
    save_benchmark_manifest,
    screen_residual_candidate,
    screen_residual_candidate_with_timeout,
)

__all__ = [
    "append_export_record",
    "BenchmarkManifest",
    "BenchmarkManifestEntry",
    "ConflictRecord",
    "CoordinatorResult",
    "MergeResult",
    "PDFRepairCoordinator",
    "ProposalClaim",
    "RepairAction",
    "RepairContext",
    "RepairProposal",
    "ViolationRef",
    "aggregate_benchmark_rows",
    "build_benchmark_record",
    "build_residual_benchmark_manifest",
    "build_coordinator_export_record",
    "classify_violation_domain",
    "compute_document_hash",
    "count_acceptance_warnings",
    "dominant_domain_from_counts",
    "load_benchmark_manifest",
    "merge_specialist_proposals",
    "normalize_acceptance_violations",
    "ResidualCandidateResult",
    "run_benchmark_entry",
    "run_discovery_seed",
    "run_manifest_benchmark",
    "run_specialist_pdf_repair",
    "save_benchmark_manifest",
    "screen_residual_candidate",
    "screen_residual_candidate_with_timeout",
    "summarize_coordinator_trace",
]
